export const sampleExperience = [
    {
        cardId: 1,
        mainImg: "/next.png",
        imgUrl: "/html.png",
        imgUrl2: "/css.png",
        imgUrl3: "/react.png",
        imgUrl4: "/ts.png",
        title  : "NEXT.Js",
        description : "reactフレームワーク",
        point  : "SSGによるビルド時生成とSSRによるサーバー側でのレンダリングの使い分けで表示速度を上げれる",
        point1 : "ファイルベースルーティングが簡単",
        point2 : "FastRefresh機能により開発サーバが高速でリロードされるため開発が楽しい",
        point3 : "新たに覚えることが少なく、jsのさまざまなライブラリを組み合わせて開発できる",
        point4 : "vercelとの連携で簡単に安心してデプロイできる",
    },
    {
        cardId: 2,
        mainImg: "/tailwindcss.png",
        imgUrl : "/html.png",
        imgUrl2: "/css.png",
        imgUrl3: "/icons8-反応する-200.png",
        imgUrl4: "/ts.png",
        title  : "tailwind css",
        description : "cssフレームワーク",
        point  : "HTMLを離れることなく、モダンなWebサイトを素早く構築できる。",
        point1 : "カスタム構成ファイルを作成し、オリジナルのスタイルを定義できる",
        point2 : "cssクラスの命名がいらない",
        point3 : "自由度が高い",
        point4 : "-",
    },
    {
        cardId: 3,
        mainImg: "/chakra.png",
        imgUrl : "/html.png",
        imgUrl2: "/css.png",
        imgUrl3: "/react.png",
        imgUrl4: "/ts.png",
        title  : "chakra UI",
        description : "cssフレームワーク",
        point  : "一貫性のあるUIを構築できる",
        point1 : "1からcssを書かなくても、UIを作れる",
        point2 : "ある程度は自分でスタイルを決めれるて、汎用性が高い",
        point3 : "-",
        point4 : "-",
    },
    {
        cardId: 4,
        mainImg: "/react.png",
        imgUrl : "/html.png",
        imgUrl2: "/css.png",
        imgUrl3: "/javascript.png",
        imgUrl4: "/ts.png",
        title  : "React",
        description : "javascriptフレームワーク",
        point  : "コンポーネント思考",
        point1 : "必要な部分だけが更新される仮想DOMのおかげ表示が高速",
        point2 : "JSX記法",
        point3 : "SPAアプリケーションの開発に向いています。",
        point4 : "JavaScriptのライブラリとして将来性が高い",
    },
    {
        cardId: 5,
        mainImg: "/motion2.png",
        imgUrl : "/html.png",
        imgUrl2: "/css.png",
        imgUrl3: "/javascript.png",
        imgUrl4: "/ts.png",
        title  : "framer-motion",
        description : "React(Library)",
        point  : "たくさんの API が提供されており、表現自体も自分の思う通りにできるくらい豊か",
        point1 : "基本的なアニメーションを実装する場合にはFramer-Motionを使えば事足りる。",
        point2 : "タップ時のモーションアニメーションから、状態遷移時のアニメーションまで、簡単に実装することができる",
        point3 : "楽しい",
        point4 : "他のJavaScriptのライブラリと相性がいい",
    },
]